import type { ThemeConfig } from './types'
import { easeOutExpo } from '@/lib/motion'

const m = {
  duration: 0.6,
  durationFast: 0.2,
  durationSlow: 0.9,
  ease: easeOutExpo,
  stagger: 0.12,
  parallax: true,
} as const

export const v1: ThemeConfig = {
  id: 'v1',
  name: 'Rooftop Sunrise',
  tokens: {
    bg: 'bg-night',
    bgAlt: 'bg-charcoal',
    bgCard: 'bg-charcoal/50',
    text: 'text-cream',
    textMuted: 'text-sand/70',
    textInverse: 'text-night',
    accent: 'bg-gold',
    accentHover: 'bg-gold-light',
    accentText: 'text-gold',
    neutral: 'text-sand',
    border: 'border-cream/5',
    borderLight: 'border-cream/10',
  },
  fonts: { display: 'font-display', body: 'font-sans' },
  motion: { ...m },
  components: {
    heroOverlay: 'bg-black/55 backdrop-blur-[2px] bg-gradient-to-t from-night via-transparent to-night/40',
    heroOverlayStyle: 'dark',
    cardRadius: 'rounded-sm',
    cardBorder: 'border border-cream/5',
    cardHover: 'hover:border-gold/20 hover:shadow-[0_0_30px_-10px_#B08D57]',
    button: 'bg-gold text-night hover:bg-gold-light hover:shadow-[0_0_30px_-5px_#B08D57]',
    buttonSecondary: 'border border-cream/20 text-cream hover:border-cream/40',
    sectionDivider: 'bg-gold/40',
    progressBar: 'bg-gradient-to-r from-gold to-gold-light',
    progressTrack: 'bg-charcoal',
  },
}

export const v2: ThemeConfig = {
  ...v1,
  id: 'v2',
  name: 'Rooftop Sunrise Clara',
  tokens: {
    bg: 'bg-cream',
    bgAlt: 'bg-sand/10',
    bgCard: 'bg-white/60',
    text: 'text-charcoal',
    textMuted: 'text-charcoal/50',
    textInverse: 'text-cream',
    accent: 'bg-[#C9A95C]',
    accentHover: 'bg-[#D4B97A]',
    accentText: 'text-[#C9A95C]',
    neutral: 'text-sand',
    border: 'border-charcoal/5',
    borderLight: 'border-charcoal/10',
  },
  components: {
    heroOverlay: 'bg-white/60 backdrop-blur-[2px] bg-gradient-to-t from-cream via-transparent to-cream/40',
    heroOverlayStyle: 'light',
    cardRadius: 'rounded-sm',
    cardBorder: 'border border-charcoal/5',
    cardHover: 'hover:border-[#C9A95C]/20 hover:shadow-[0_0_30px_-10px_#C9A95C]',
    button: 'bg-[#C9A95C] text-cream hover:bg-[#D4B97A] hover:shadow-[0_0_30px_-5px_#C9A95C]',
    buttonSecondary: 'border border-charcoal/20 text-charcoal hover:border-charcoal/40',
    sectionDivider: 'bg-[#C9A95C]/40',
    progressBar: 'bg-gradient-to-r from-[#C9A95C] to-[#D4B97A]',
    progressTrack: 'bg-charcoal/5',
  },
}

export const v3: ThemeConfig = {
  ...v1,
  id: 'v3',
  name: 'Night Athletic',
  tokens: {
    bg: 'bg-[#0D0D0F]',
    bgAlt: 'bg-[#1A1A1E]',
    bgCard: 'bg-[#1A1A1E]/50',
    text: 'text-white',
    textMuted: 'text-white/50',
    textInverse: 'text-[#0D0D0F]',
    accent: 'bg-[#CFFF04]',
    accentHover: 'bg-[#DDFF44]',
    accentText: 'text-[#CFFF04]',
    neutral: 'text-[#2A2A2E]',
    border: 'border-white/5',
    borderLight: 'border-white/10',
  },
  fonts: { display: 'font-archivo', body: 'font-sans' },
  motion: { ...m, duration: 0.3, durationFast: 0.15, durationSlow: 0.5, parallax: false },
  components: {
    heroOverlay: 'bg-[#0D0D0F]/70',
    heroOverlayStyle: 'dark',
    cardRadius: 'rounded-none',
    cardBorder: 'border border-white/5',
    cardHover: 'hover:border-[#CFFF04]/30',
    button: 'bg-[#CFFF04] text-[#0D0D0F] hover:bg-[#DDFF44] active:shadow-[0_0_30px_-5px_#CFFF04]',
    buttonSecondary: 'border border-white/20 text-white hover:border-white/40',
    sectionDivider: 'bg-[#CFFF04]/40',
    progressBar: 'bg-[#CFFF04]',
    progressTrack: 'bg-[#2A2A2E]',
  },
}
