import type { ThemeConfig } from './types'
import { easeOutExpo } from '@/lib/motion'

const base = {
  duration: 0.6,
  durationFast: 0.2,
  durationSlow: 0.9,
  ease: easeOutExpo,
  stagger: 0.12,
  parallax: true,
} as const

export const v4: ThemeConfig = {
  id: 'v4',
  name: 'Editorial Mono',
  tokens: {
    bg: 'bg-black',
    bgAlt: 'bg-[#111]',
    bgCard: 'bg-black',
    text: 'text-white',
    textMuted: 'text-[#8A8A8A]',
    textInverse: 'text-black',
    accent: 'bg-white',
    accentHover: 'bg-[#ddd]',
    accentText: 'text-white',
    neutral: 'text-[#8A8A8A]',
    border: 'border-white/10',
    borderLight: 'border-white/5',
  },
  fonts: { display: 'font-display', body: 'font-sans' },
  motion: { ...base, duration: 0.9, durationFast: 0.4, durationSlow: 1.2, parallax: false },
  components: {
    heroOverlay: 'bg-black/40',
    heroOverlayStyle: 'dark',
    cardRadius: 'rounded-none',
    cardBorder: 'border-0 border-t border-white/10',
    cardHover: 'hover:bg-white/5',
    button: 'bg-white text-black hover:bg-[#ddd]',
    buttonSecondary: 'border border-white/20 text-white hover:border-white/40',
    sectionDivider: 'bg-white/20',
    progressBar: 'bg-white',
    progressTrack: 'bg-[#222]',
  },
}

export const v5: ThemeConfig = {
  id: 'v5',
  name: 'Beach Club Tropical',
  tokens: {
    bg: 'bg-[#F4E9DA]',
    bgAlt: 'bg-[#EDDFCC]',
    bgCard: 'bg-white/50',
    text: 'text-[#2C2420]',
    textMuted: 'text-[#2C2420]/50',
    textInverse: 'text-[#F4E9DA]',
    accent: 'bg-[#E0876A]',
    accentHover: 'bg-[#E69A82]',
    accentText: 'text-[#E0876A]',
    neutral: 'text-[#5C6B4D]',
    border: 'border-[#2C2420]/5',
    borderLight: 'border-[#2C2420]/10',
  },
  fonts: { display: 'font-poppins', body: 'font-sans' },
  motion: { ...base, duration: 0.7, durationFast: 0.25, durationSlow: 1, parallax: true },
  components: {
    heroOverlay: 'bg-gradient-to-b from-[#F4E9DA]/20 via-[#F4E9DA]/40 to-[#F4E9DA]/60',
    heroOverlayStyle: 'light',
    cardRadius: 'rounded-xl',
    cardBorder: 'border border-[#2C2420]/5',
    cardHover: 'hover:border-[#E0876A]/20 hover:shadow-[0_8px_30px_-10px_#E0876A]',
    button: 'bg-[#E0876A] text-white hover:bg-[#E69A82]',
    buttonSecondary: 'border border-[#2C2420]/20 text-[#2C2420] hover:border-[#2C2420]/40',
    sectionDivider: 'bg-[#E0876A]/30',
    progressBar: 'bg-gradient-to-r from-[#E0876A] to-[#C9923C]',
    progressTrack: 'bg-[#2C2420]/5',
  },
}

export const v6: ThemeConfig = {
  id: 'v6',
  name: 'Performance Tech',
  tokens: {
    bg: 'bg-[#1A1D21]',
    bgAlt: 'bg-[#22262B]',
    bgCard: 'bg-[#22262B]/50',
    text: 'text-[#E8EAED]',
    textMuted: 'text-[#9CA3AF]',
    textInverse: 'text-[#1A1D21]',
    accent: 'bg-[#5B8DEF]',
    accentHover: 'bg-[#7BA3F0]',
    accentText: 'text-[#5B8DEF]',
    neutral: 'text-[#9CA3AF]',
    border: 'border-[#E8EAED]/5',
    borderLight: 'border-[#E8EAED]/10',
  },
  fonts: { display: 'font-space-grotesk', body: 'font-sans' },
  motion: { ...base, duration: 0.4, durationFast: 0.15, durationSlow: 0.6, parallax: false },
  components: {
    heroOverlay: 'bg-[#1A1D21]/70',
    heroOverlayStyle: 'dark',
    cardRadius: 'rounded-sm',
    cardBorder: 'border border-[#E8EAED]/5',
    cardHover: 'hover:border-[#5B8DEF]/30',
    button: 'bg-[#5B8DEF] text-white hover:bg-[#7BA3F0]',
    buttonSecondary: 'border border-[#E8EAED]/20 text-[#E8EAED] hover:border-[#E8EAED]/40',
    sectionDivider: 'bg-[#5B8DEF]/30',
    progressBar: 'bg-[#5B8DEF]',
    progressTrack: 'bg-[#22262B]',
  },
}

export const v7: ThemeConfig = {
  id: 'v7',
  name: 'Luxury Spa Wellness',
  tokens: {
    bg: 'bg-[#F7F3EC]',
    bgAlt: 'bg-[#EFE9DF]',
    bgCard: 'bg-white/50',
    text: 'text-[#2C2420]',
    textMuted: 'text-[#2C2420]/40',
    textInverse: 'text-[#F7F3EC]',
    accent: 'bg-[#C9B79C]',
    accentHover: 'bg-[#D4C5AE]',
    accentText: 'text-[#C9B79C]',
    neutral: 'text-[#7C8A72]',
    border: 'border-[#2C2420]/5',
    borderLight: 'border-[#2C2420]/8',
  },
  fonts: { display: 'font-cormorant', body: 'font-sans' },
  motion: { ...base, duration: 1, durationFast: 0.4, durationSlow: 1.4, parallax: true },
  components: {
    heroOverlay: 'bg-gradient-to-b from-[#F7F3EC]/10 via-transparent to-[#F7F3EC]/30',
    heroOverlayStyle: 'light',
    cardRadius: 'rounded-none',
    cardBorder: 'border-0 border-t border-[#2C2420]/5',
    cardHover: 'hover:bg-[#2C2420]/[0.02]',
    button: 'bg-[#C9B79C] text-[#F7F3EC] hover:bg-[#D4C5AE]',
    buttonSecondary: 'border border-[#2C2420]/15 text-[#2C2420] hover:border-[#2C2420]/30',
    sectionDivider: 'bg-[#C9B79C]/30',
    progressBar: 'bg-gradient-to-r from-[#C9B79C] to-[#7C8A72]',
    progressTrack: 'bg-[#2C2420]/5',
  },
}
